### ISSUE TITLE
Error loading solution

### ISSUE THREAD

**Issue by ghost** [dhana29/ReportViewer-control-to-replace-iFrame-on-MVC-Project#1]
Hi,
This looks like it could be just what we need.
I got the following error trying to loading the solution - the csproj file seems to be missing.
error  : The project file could not be loaded. Could not find file 'C:\<path>\SSRSReportViewByiFrame\SSRSReportViewByiFrame.csproj'.

Thanks.

**Comment by dhana29** [comment]
I have added **SSRSReportViewByiFrame.csproj** file. Please check it out. Thank you.

**Comment by ghost** [comment]
Hi, thanks, that has enabled me to open the project, but it shows many files missing. Image attached.
![image](https://user-images.githubusercontent.com/15825150/45337604-fc973280-b5dc-11e8-9a64-e038b809d923.png)

**Comment by dhana29** [comment]
I have uploaded all the files. Download and try. or you can just create an MVC Template application and replace the files listed in the Readme.

Make sure to add values for web.config items listed in the Readme.

Happy coding!

**Comment by ghost** [comment]
Thanks for your help.
